### ISSUE TITLE
Split C++ and Python in two different directory

### ISSUE THREAD

**Issue by isazi** [LHC-NLeSC/ghostprob#1]
It is probably better if we split the C++ and Python in two separate subdirectories.

@goord I will create a `python` directory and move my files there, you can do the `cpp` one.

**Comment by goord** [comment]
absolutely go ahead, I'm just dumping everything in the repo

**Comment by goord** [comment]
ok, the data can also go in a separate directory I think

**Comment by isazi** [comment]
Good idea, let's also make a `data` directory.

**Comment by isazi** [comment]
Done with all the repo refactoring.
